### ISSUE TITLE
PDM_Filter output of its 1st 2 PCM-converted data seems to be erroneous

### ISSUE THREAD

**Issue by VictorTagayun** [siorpaes/pdmgenerator#1]
Not an issue but an inquiry.

Do you encounter the 1st 2 PCM-converted data seems to be erroneous?

I posted in ST Community in this link https://community.st.com/s/question/0D53W000019CZzmSAG/pdmfilter-erroneous-1st-2-pcmconverted-data

I asked here because I used you PDM tones.

**Comment by siorpaes** [comment]
Hello, I guess the problem is related to inherent FIR filter transient response. You need to wait at least N-1 samples, where N is the length of the filter, to have correct data.
See, for example,

https://www.dsprelated.com/freebooks/filters/Transient_Response_Steady_State.html
